import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SectionContainer from "@/components/SectionContainer";
import { ThemeContextProvider } from "@/context/theme";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <ThemeContextProvider>
          <body className="bg-white text-black  antialiased dark:bg-gray-950 dark:text-white">
            <SectionContainer>
              <Header></Header>
              {children}
            </SectionContainer>
          </body>
        </ThemeContextProvider>
      </html>
    </ClerkProvider>
  );
}
